import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Github, Sparkles, Loader2, X, ArrowUpRight } from 'lucide-react';
import { PROJECTS } from '../data/portfolioData';
import { Project } from '../types';
import { callGemini } from '../services/gemini';
import { SectionHeading } from './ui/SectionHeading';
import { ProjectCover } from './ui/ProjectCover';

const ease = [0.16, 1, 0.3, 1] as const;

function Stats({ items }: { items: string[] }) {
  return (
    <ul className="flex flex-wrap gap-1.5">
      {items.map(item => (
        <li key={item} className="px-2 py-0.5 rounded-md bg-canvas text-[12px] font-medium text-body tabular-nums">
          {item}
        </li>
      ))}
    </ul>
  );
}

function AIInsight({ project }: { project: Project }) {
  const [insight, setInsight] = useState('');
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    const res = await callGemini(
      `Suggest a future technical direction for the project: "${project.title}" which uses ${project.tools}.`,
      'You are a Senior Bioinformatics Advisor. Be concise.'
    );
    setInsight(res);
    setLoading(false);
  }

  if (insight) {
    return (
      <div className="rounded-xl bg-accent-soft p-4">
        <p className="flex items-center gap-2 text-[12px] font-semibold text-accent"><Sparkles size={14} /> AI insight</p>
        <p className="mt-2 text-sm text-body leading-relaxed">{insight}</p>
        <p className="mt-2 text-[12px] text-muted">Generated by Gemini</p>
      </div>
    );
  }

  return (
    <button
      onClick={generate}
      disabled={loading}
      className="inline-flex items-center gap-2 text-sm font-medium text-accent hover:text-accent-hover disabled:opacity-60 transition-colors"
    >
      {loading ? <Loader2 size={15} className="animate-spin" /> : <Sparkles size={15} />}
      {loading ? 'Thinking…' : 'Suggest a next step with AI'}
    </button>
  );
}

function ProjectDetails({ project, onClose }: { project: Project | null; onClose: () => void }) {
  useEffect(() => {
    if (!project) return;
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [project, onClose]);

  return (
    <AnimatePresence>
      {project && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          onClick={onClose}
          className="fixed inset-0 z-[60] bg-black/30 backdrop-blur-sm flex items-center justify-center p-4"
        >
          <motion.div
            role="dialog"
            aria-modal="true"
            aria-label={project.title}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            transition={{ duration: 0.3, ease }}
            onClick={e => e.stopPropagation()}
            className="relative bg-surface w-full max-w-xl max-h-[88vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col"
          >
            <div className="relative shrink-0">
              <ProjectCover kind={project.cover} className="block w-full aspect-[16/7]" />
              <button
                onClick={onClose}
                aria-label="Close project details"
                autoFocus
                className="absolute top-3 right-3 w-9 h-9 flex items-center justify-center bg-surface/90 backdrop-blur rounded-full text-ink hover:bg-surface transition-colors"
              >
                <X size={18} />
              </button>
            </div>

            <div className="p-6 sm:p-7 overflow-y-auto custom-scrollbar">
              <p className="text-[12px] font-medium text-muted uppercase tracking-wide">{project.tools.split(' | ').join(' · ')}</p>
              <h3 className="mt-2 text-xl font-semibold tracking-tight text-ink">{project.title}</h3>
              <div className="mt-3"><Stats items={project.stats} /></div>
              <p className="mt-4 text-[15px] text-body leading-relaxed">{project.desc}</p>

              <h4 className="mt-6 text-sm font-semibold text-ink">Methods</h4>
              <ul className="mt-2 space-y-1.5">
                {project.features.map(feature => (
                  <li key={feature} className="flex gap-2.5 text-[15px] text-body leading-snug">
                    <span className="mt-[0.5rem] w-1.5 h-1.5 rounded-full bg-accent shrink-0" />
                    {feature}
                  </li>
                ))}
              </ul>

              <div className="mt-6"><AIInsight project={project} /></div>

              <div className="mt-6 pt-5 border-t border-black/5 flex justify-end">
                <a
                  href={project.link}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 bg-ink text-white px-4 py-2.5 rounded-lg text-sm font-medium hover:bg-accent transition-colors"
                >
                  <Github size={16} /> View code on GitHub
                </a>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

function ProjectCard({ project, large, onOpen, delay }: { project: Project; large: boolean; onOpen: () => void; delay: number }) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.5, delay, ease }}
      className="group flex flex-col bg-surface rounded-2xl ring-1 ring-black/5 overflow-hidden hover:ring-black/10 hover:shadow-[0_12px_32px_-16px_rgba(0,0,0,0.25)] transition-shadow duration-300"
    >
      <div onClick={onOpen} className="cursor-pointer overflow-hidden">
        <ProjectCover
          kind={project.cover}
          className={`block w-full ${large ? 'aspect-[16/7]' : 'aspect-[16/7] sm:aspect-[16/9]'} transition-transform duration-500 group-hover:scale-[1.02]`}
        />
      </div>

      <div className={`flex flex-col flex-1 ${large ? 'p-6' : 'p-5'}`}>
        <p className="text-[12px] font-medium text-muted uppercase tracking-wide truncate">{project.tools.split(' | ').slice(0, 3).join(' · ')}</p>
        <h3 className={`mt-1.5 font-semibold tracking-tight text-ink leading-snug ${large ? 'text-lg' : 'text-base'}`}>
          <button onClick={onOpen} className="text-left hover:text-accent transition-colors">{project.title}</button>
        </h3>
        <p className={`mt-2 text-sm text-body leading-relaxed ${large ? '' : 'line-clamp-3'}`}>{project.desc}</p>

        <div className="mt-4"><Stats items={project.stats} /></div>

        <div className="mt-auto pt-5 flex items-center gap-4 text-sm font-medium">
          <button onClick={onOpen} className="inline-flex items-center gap-1 text-accent hover:text-accent-hover transition-colors">
            Details <ArrowUpRight size={15} />
          </button>
          <a
            href={project.link}
            target="_blank"
            rel="noreferrer"
            aria-label={`Source code for ${project.title} on GitHub`}
            className="inline-flex items-center gap-1.5 text-muted hover:text-ink transition-colors"
          >
            <Github size={15} /> Code
          </a>
        </div>
      </div>
    </motion.article>
  );
}

export default function Projects() {
  const [selected, setSelected] = useState<Project | null>(null);
  const pipelines = PROJECTS.filter(p => p.kind === 'pipeline');
  const analyses = PROJECTS.filter(p => p.kind === 'analysis');

  return (
    <section id="projects" className="py-8 md:py-10">
      <div className="max-w-6xl mx-auto px-6 w-full">
        <SectionHeading title="Selected projects" subtitle="Reproducible pipelines and single-cell analyses, each framed around a biological question." />

        <h3 className="text-sm font-semibold text-muted mb-4">Pipelines</h3>
        <div className="grid md:grid-cols-2 gap-5">
          {pipelines.map((p, i) => <React.Fragment key={p.link}><ProjectCard project={p} large delay={i * 0.06} onOpen={() => setSelected(p)} /></React.Fragment>)}
        </div>

        <h3 className="text-sm font-semibold text-muted mt-10 mb-4">Analyses</h3>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {analyses.map((p, i) => <React.Fragment key={p.link}><ProjectCard project={p} large={false} delay={i * 0.06} onOpen={() => setSelected(p)} /></React.Fragment>)}
        </div>
      </div>

      <ProjectDetails project={selected} onClose={() => setSelected(null)} />
    </section>
  );
}
