import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Globe, Github, Sparkles, Loader2, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { PROJECTS } from '../data/portfolioData';
import { Project } from '../types';
import { callGemini } from '../services/gemini';
import { ParallaxBackground } from './ui/ParallaxBackground';
import { SectionHeading } from './ui/SectionHeading';

function AIProjectInsight({ project, onOpenChange }: { project: Project; onOpenChange?: (isOpen: boolean) => void }) {
  const [insight, setInsight] = useState("");
  const [loading, setLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  // Notify parent component when modal state changes
  useEffect(() => {
    if (onOpenChange) {
      onOpenChange(isOpen);
    }
  }, [isOpen, onOpenChange]);

  async function getInsight() {
    if (insight) {
        setIsOpen(true);
        return;
    }
    setLoading(true);
    const res = await callGemini(`Suggest a future technical direction for the project: "${project.title}" which uses ${project.tools}.`, "You are a Senior Bioinformatics Advisor. Be concise.");
    setInsight(res);
    setLoading(false);
    setIsOpen(true);
  }

  return (
    <>
      <div className="mt-auto pt-3 border-t border-black/5 w-full">
        <button 
          onClick={getInsight} 
          disabled={loading} 
          className="flex items-center gap-2 text-[10px] font-bold text-[#0071e3] uppercase tracking-widest hover:text-[#005bb5] transition-colors group w-full justify-center py-2 hover:bg-blue-50/50 rounded-lg"
        >
          {loading ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} className="group-hover:scale-110 transition-transform" />} 
          <span>{insight ? "View AI Insight" : "Generate AI Insight"}</span>
        </button>
      </div>

      <AnimatePresence>
        {isOpen && (
          <motion.div 
            initial={{ opacity: 0, backdropFilter: "blur(0px)" }}
            animate={{ opacity: 1, backdropFilter: "blur(12px)" }}
            exit={{ opacity: 0, backdropFilter: "blur(0px)" }}
            className="absolute inset-0 z-50 bg-white/95 p-6 flex flex-col text-left rounded-[2.5rem]"
          >
             <div className="flex justify-between items-center mb-4 border-b border-black/5 pb-2">
                <div className="flex items-center gap-2 text-[#0071e3]">
                   <Sparkles size={16} />
                   <span className="text-[11px] font-bold uppercase tracking-widest">AI Analysis</span>
                </div>
                <button 
                  onClick={(e) => { e.stopPropagation(); setIsOpen(false); }}
                  className="p-1.5 hover:bg-black/5 rounded-full text-[#86868b] transition-colors"
                >
                  <X size={18} />
                </button>
             </div>
             
             <div className="flex-grow overflow-y-auto custom-scrollbar pr-1">
                <p className="text-[13px] leading-relaxed text-[#1d1d1f] font-medium">
                  {insight}
                </p>
             </div>
             
             <div className="mt-4 pt-3 border-t border-black/5 text-center">
                <p className="text-[10px] text-[#86868b]">Generated by Gemini 2.5 Flash</p>
             </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

function ProjectDetailsModal({ project, isOpen, onClose }: { project: Project | null; isOpen: boolean; onClose: () => void }) {
  if (!project) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/30 backdrop-blur-sm z-[60] flex items-center justify-center p-4"
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed z-[70] bg-white w-full max-w-2xl max-h-[85vh] rounded-[2rem] shadow-2xl overflow-hidden flex flex-col top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
          >
            <div className="relative h-48 sm:h-64 w-full shrink-0">
              {project.image ? (
                <img src={project.image} alt={project.title} className="w-full h-full object-cover" />
              ) : (
                <div className="w-full h-full flex items-center justify-center bg-gray-100 text-gray-300">
                  <Globe size={64} />
                </div>
              )}
              <button
                onClick={onClose}
                className="absolute top-4 right-4 p-2 bg-white/80 backdrop-blur rounded-full text-black/60 hover:text-black transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            <div className="p-6 sm:p-8 overflow-y-auto custom-scrollbar">
              <h3 className="text-2xl font-bold text-[#1d1d1f] mb-2">{project.title}</h3>
              <p className="text-[#0071e3] font-bold text-sm uppercase tracking-wider mb-6">{project.tools}</p>

              <div className="space-y-6">
                <div>
                  <h4 className="text-sm font-bold text-[#1d1d1f] uppercase tracking-wide mb-2">Overview</h4>
                  <p className="text-[#424245] leading-relaxed">{project.desc}</p>
                </div>

                {project.features && (
                  <div>
                    <h4 className="text-sm font-bold text-[#1d1d1f] uppercase tracking-wide mb-2">Key Features</h4>
                    <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {project.features.map((feature, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-[#424245] text-sm">
                          <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-[#0071e3] shrink-0" />
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {project.tags && (
                  <div className="flex flex-wrap gap-2">
                    {project.tags.map((tag, idx) => (
                      <span key={idx} className="px-3 py-1 bg-[#F5F5F7] text-[#86868b] text-xs font-medium rounded-full border border-black/5">
                        {tag}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              <div className="mt-8 pt-6 border-t border-black/5 flex justify-end">
                <a
                  href={project.link}
                  target="_blank"
                  rel="noreferrer"
                  className="bg-[#1d1d1f] text-white px-6 py-3 rounded-xl font-bold text-sm flex items-center gap-2 hover:bg-[#0071e3] transition-colors"
                >
                  View Source Code <Github size={16} />
                </a>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

function ProjectDockCarousel({ onOpenAi }: { onOpenAi?: (isOpen: boolean) => void }) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [isAutoPlaying, setIsAutoPlaying] = useState(true);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Auto-play logic
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isAutoPlaying && !selectedProject) {
      interval = setInterval(() => {
        setActiveIndex((prev) => (prev + 1) % PROJECTS.length);
      }, 5000);
    }
    return () => clearInterval(interval);
  }, [isAutoPlaying, selectedProject]);

  const handleDragEnd = (event: any, info: any) => {
    if (info.offset.x > 50) {
      setActiveIndex((prev) => (prev - 1 + PROJECTS.length) % PROJECTS.length);
    } else if (info.offset.x < -50) {
      setActiveIndex((prev) => (prev + 1) % PROJECTS.length);
    }
    setIsAutoPlaying(true);
  };

  const handleCardClick = (index: number, isCenter: boolean) => {
    if (isCenter) {
      setSelectedProject(PROJECTS[index]);
      setIsAutoPlaying(false);
    } else {
      setActiveIndex(index);
    }
  };

  const getCardProps = (index: number) => {
    // Calculate distance from active index (circular)
    const length = PROJECTS.length;
    let distance = (index - activeIndex + length) % length;
    
    // Normalize distance to be centered around 0 (e.g. -2, -1, 0, 1, 2)
    if (distance > length / 2) distance -= length;
    if (distance < -length / 2) distance += length;

    // Determine visual properties based on distance
    const isCenter = distance === 0;
    const isAdjacent = Math.abs(distance) === 1;
    const isVisible = Math.abs(distance) <= 2; // Show only 2 neighbors on each side (optional)

    return {
      distance,
      isCenter,
      isAdjacent,
      isVisible
    };
  };

  return (
    <>
      <div 
        className="relative w-full h-[400px] flex items-center justify-center overflow-hidden" 
        ref={containerRef}
        onMouseEnter={() => setIsAutoPlaying(false)}
        onMouseLeave={() => !selectedProject && setIsAutoPlaying(true)}
      >
        <div className="relative w-full max-w-5xl h-full flex items-center justify-center perspective-[1000px]">
          {PROJECTS.map((project, index) => {
            const { distance, isCenter, isAdjacent } = getCardProps(index);
            
            return (
              <motion.div
                key={index}
                drag="x"
                dragConstraints={{ left: 0, right: 0 }}
                dragElastic={0.1}
                onDragEnd={handleDragEnd}
                animate={{
                  x: distance * 320, // Horizontal spacing
                  scale: isCenter ? 1 : isAdjacent ? 0.85 : 0.7,
                  opacity: isCenter ? 1 : isAdjacent ? 0.6 : 0.3,
                  zIndex: isCenter ? 10 : 5 - Math.abs(distance),
                  rotateY: distance * -15, // Subtle 3D rotation
                  filter: isCenter ? 'blur(0px)' : 'blur(2px)',
                }}
                transition={{
                  type: "spring",
                  stiffness: 260,
                  damping: 20
                }}
                onClick={() => handleCardClick(index, isCenter)}
                className={`absolute w-[300px] md:w-[360px] h-[400px] bg-white rounded-[2rem] shadow-xl border border-white/50 overflow-hidden cursor-pointer ${isCenter ? 'pointer-events-auto' : 'pointer-events-none md:pointer-events-auto'}`}
                style={{
                  transformStyle: 'preserve-3d',
                  boxShadow: isCenter 
                    ? '0 25px 50px -12px rgba(0, 0, 0, 0.25)' 
                    : '0 10px 15px -3px rgba(0, 0, 0, 0.1)'
                }}
              >
                {/* Project Content */}
                <div className="flex flex-col h-full p-6">
                  {/* Image Area */}
                  <div className="h-32 w-full rounded-2xl overflow-hidden mb-4 border border-black/5 bg-gray-50 shrink-0 relative group">
                     {project.image ? (
                       <img src={project.image} alt={project.title} className="w-full h-full object-cover" />
                     ) : (
                       <div className="w-full h-full flex items-center justify-center text-gray-300"><Globe size={40} /></div>
                     )}
                     {isCenter && (
                       <>
                        <div className="absolute top-2 right-2 bg-white/90 backdrop-blur px-2 py-1 rounded-full text-[10px] font-bold text-[#0071e3] shadow-sm z-10">
                            Active
                        </div>
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors flex items-center justify-center">
                            <span className="opacity-0 group-hover:opacity-100 bg-white/90 backdrop-blur px-3 py-1.5 rounded-full text-xs font-bold text-[#1d1d1f] shadow-sm transition-opacity transform scale-95 group-hover:scale-100">
                                Click to Expand
                            </span>
                        </div>
                       </>
                     )}
                  </div>

                  {/* Text Content */}
                  <div className="flex-grow flex flex-col">
                    <h3 className="text-[15px] font-bold text-[#1d1d1f] leading-snug mb-1 line-clamp-2">{project.title}</h3>
                    <p className="text-[10px] font-bold text-[#0071e3] uppercase tracking-wider mb-2">{project.tools}</p>
                    
                    <p className="text-[12px] text-[#424245] leading-relaxed line-clamp-3 mb-3 flex-grow">
                      {project.desc}
                    </p>
                    
                    {/* Action Area */}
                    <div className="mt-auto space-y-3">
                       <div className="flex gap-2">
                          <a 
                            href={project.link}
                            target="_blank"
                            rel="noreferrer"
                            className="flex-1 bg-[#1d1d1f] text-white text-[12px] font-bold py-2.5 rounded-xl flex items-center justify-center gap-2 hover:bg-[#0071e3] transition-colors"
                            onClick={(e) => e.stopPropagation()}
                          >
                            View Code <Github size={14} />
                          </a>
                       </div>
                       
                       {/* AI Component */}
                       <div onClick={(e) => e.stopPropagation()}>
                        <AIProjectInsight project={project} onOpenChange={onOpenAi} />
                       </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Navigation Dots */}
        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 z-20">
          {PROJECTS.map((_, idx) => (
            <button
              key={idx}
              onClick={() => setActiveIndex(idx)}
              className={`w-1.5 h-1.5 rounded-full transition-all duration-300 ${activeIndex === idx ? 'bg-[#0071e3] w-4' : 'bg-gray-300 hover:bg-gray-400'}`}
            />
          ))}
        </div>
        
         {/* Arrow Controls */}
         <div className="absolute inset-0 pointer-events-none flex items-center justify-between px-4 md:px-12 z-10">
            <button 
              onClick={() => setActiveIndex((prev) => (prev - 1 + PROJECTS.length) % PROJECTS.length)}
              className="w-10 h-10 rounded-full bg-white/80 backdrop-blur shadow-md flex items-center justify-center text-[#1d1d1f] hover:scale-110 active:scale-95 transition-all pointer-events-auto border border-white/50"
            >
               <ChevronLeft size={20} />
            </button>
            <button 
              onClick={() => setActiveIndex((prev) => (prev + 1) % PROJECTS.length)}
              className="w-10 h-10 rounded-full bg-white/80 backdrop-blur shadow-md flex items-center justify-center text-[#1d1d1f] hover:scale-110 active:scale-95 transition-all pointer-events-auto border border-white/50"
            >
               <ChevronRight size={20} />
            </button>
         </div>
      </div>

      <ProjectDetailsModal 
        project={selectedProject} 
        isOpen={!!selectedProject} 
        onClose={() => {
          setSelectedProject(null);
          setIsAutoPlaying(true);
        }} 
      />
    </>
  );
}

export default function Projects({ onOpenAi }: { onOpenAi?: (isOpen: boolean) => void }) {
    return (
        <section id="projects" className="min-h-screen pt-20 pb-20 bg-[#F5F5F7] flex items-start justify-center relative overflow-hidden">
        <ParallaxBackground />
          
        <div className="max-w-7xl mx-auto px-6 w-full relative z-10 flex flex-col justify-center">
          <SectionHeading title="Selected Projects" />
            
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <ProjectDockCarousel onOpenAi={onOpenAi} />
          </motion.div>
        </div>
      </section>
    );
}